GET https://us-central1-foodpick-291fe.cloudfunctions.net/api/getdonations



###

GET http://localhost:3000/getdonation/65f308ef9d39773fe7c27e41



###

POST https://us-central1-foodpick-291fe.cloudfunctions.net/api/postdonation
Content-Type: application/json

{
  "foodName": "pasta",
  "feedsCount": 2,
  "donorAddress": {
    "latitude": 45.64811801941689,
    "longitude": -0.2095857858718817
  }
}


###

DELETE http://localhost:3000/deletedonation/65f35f6d538ff523ccfd2f79